name: Legacy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        database: [ sqlite3, mysql, postgresql ]
        extension: [ core, dragonfly, images, pages, resources ]
        ruby: [ 3.2, 3.3, 3.4, 4.0 ]
        rails: [ '~> 6.1.0', '~> 7.0.0', '~> 7.1.0' ]
        exclude:
          - ruby: 3.4
            rails: '~> 6.1.0'
          - ruby: 4.0
            rails: '~> 6.1.0'
      fail-fast: false
    runs-on: ubuntu-latest

    env:
      CI: true
      DB: ${{ matrix.database }}
      MYSQL_PASSWORD: root
      PGHOST: localhost
      PGPASSWORD: runner
      PGUSER: runner
      RAILS_ENV: test
      RAILS_VERSION: ${{ matrix.rails }}
      RETRY_COUNT: 3

    name: rails ${{ matrix.rails }} ruby ${{ matrix.ruby }} refinerycms-${{ matrix.extension }} ${{ matrix.database }}
    steps:
      - run: sudo apt-get update && sudo apt-get install libsqlite3-dev -y
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: "Install ImageMagick for images extension"
        if: ${{ matrix.extension == 'images' }}
        run: sudo apt-get install imagemagick -y

      - name: "Set up MySQL using VM's server"
        if: ${{ env.DB == 'mysql' }}
        run: |
          sudo apt-get install libmysqlclient-dev -y
          sudo systemctl start mysql.service

      - name: "Set up PostgreSQL using VM's server"
        if: ${{ env.DB == 'postgresql' }}
        run: |
          sudo apt-get install libpq-dev -y
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE USER runner WITH SUPERUSER PASSWORD 'runner'"

      - run: bin/rake refinery:testing:dummy_app
      - run: bin/rspec ${{ matrix.extension }}/spec
